In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("annual_deaths_by_causes.csv")

In [3]:
df.head()

,country,code,year,meningitis,alzheimer's_diesease,parkinson's_disease,nutritional_deficiency,malaria,drowning,interpersonal_violence,...,chronic_kidney_disease,poisonings,protein_energy_malnutrition,terrorism,road_injuries,chronic_respiratory_diseases,chronic_liver_diseases,digestive_diseases,fire_heat_hot_substance,acute_hepatitis
0,Afghanistan,AFG,2007,2933.0,1402.0,450.0,2488.0,393.0,2127.0,3657.0,...,4490.0,512.0,2439.0,1199.0,7425.0,7222.0,3346.0,6458.0,481.0,3437.0
1,Afghanistan,AFG,2008,2731.0,1424.0,455.0,2277.0,255.0,1973.0,3785.0,...,4534.0,495.0,2231.0,1092.0,7355.0,7143.0,3316.0,6408.0,462.0,3005.0
2,Afghanistan,AFG,2009,2460.0,1449.0,460.0,2040.0,239.0,1852.0,3874.0,...,4597.0,483.0,1998.0,1065.0,7290.0,7045.0,3291.0,6358.0,448.0,2663.0
3,Afghanistan,AFG,2011,2327.0,1508.0,473.0,1846.0,390.0,1775.0,4170.0,...,4785.0,483.0,1805.0,1525.0,7432.0,6916.0,3318.0,6370.0,448.0,2365.0
4,Afghanistan,AFG,2012,2254.0,1544.0,482.0,1705.0,94.0,1716.0,4245.0,...,4846.0,482.0,1667.0,3521.0,7494.0,6878.0,3353.0,6398.0,445.0,2264.0

In [4]:
df["code"].value_counts()

BIH         30
TUR         30
PRI         30
TGO         30
LUX         30
            ..
OWID_USS     2
WLF          1
PYF          1
GLP          1
NCL          1
Name: code, Length: 217, dtype: int64

In [5]:
len(df)

7273

In [6]:
# df.iloc[0]

In [7]:
df.iloc[:, 2:10].head()

,year,meningitis,alzheimer's_diesease,parkinson's_disease,nutritional_deficiency,malaria,drowning,interpersonal_violence
0,2007,2933.0,1402.0,450.0,2488.0,393.0,2127.0,3657.0
1,2008,2731.0,1424.0,455.0,2277.0,255.0,1973.0,3785.0
2,2009,2460.0,1449.0,460.0,2040.0,239.0,1852.0,3874.0
3,2011,2327.0,1508.0,473.0,1846.0,390.0,1775.0,4170.0
4,2012,2254.0,1544.0,482.0,1705.0,94.0,1716.0,4245.0

In [8]:
df[df.isna().any(axis=1)]

,country,code,year,meningitis,alzheimer's_diesease,parkinson's_disease,nutritional_deficiency,malaria,drowning,interpersonal_violence,...,chronic_kidney_disease,poisonings,protein_energy_malnutrition,terrorism,road_injuries,chronic_respiratory_diseases,chronic_liver_diseases,digestive_diseases,fire_heat_hot_substance,acute_hepatitis
12,Afghanistan,AFG,1993,2812.0,1187.0,384.0,2837.0,108.0,1687.0,2589.0,...,3862.0,425.0,2797.0,NaN,5681.0,6445.0,2943.0,5568.0,396.0,3601.0
28,Afghanistan,AFG,2018,1576.0,1757.0,551.0,1279.0,466.0,1669.0,5500.0,...,5531.0,514.0,1245.0,NaN,8095.0,7036.0,3732.0,6861.0,475.0,1972.0
29,Afghanistan,AFG,2019,1563.0,1775.0,560.0,1244.0,530.0,1687.0,5015.0,...,5637.0,525.0,1210.0,NaN,8254.0,7082.0,3797.0,6929.0,485.0,1940.0
30,African Region (WHO),NaN,1990,172206.0,24312.0,6573.0,215934.0,588508.0,27182.0,50714.0,...,64609.0,17453.0,208628.0,NaN,130403.0,123351.0,119201.0,198446.0,19552.0,17666.0
31,African Region (WHO),NaN,1991,174087.0,25173.0,6754.0,216068.0,607330.0,27357.0,52671.0,...,66230.0,17461.0,208785.0,NaN,132658.0,125505.0,121587.0,202452.0,19696.0,17844.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7265,Zimbabwe,ZWE,2012,1586.0,724.0,209.0,3095.0,2763.0,754.0,1243.0,...,2004.0,366.0,3065.0,NaN,2328.0,2708.0,2011.0,4132.0,622.0,152.0
7268,Zimbabwe,ZWE,2015,1439.0,754.0,215.0,3019.0,2518.0,770.0,1302.0,...,2108.0,381.0,2990.0,NaN,2373.0,2751.0,1956.0,4202.0,632.0,146.0
7269,Zimbabwe,ZWE,2016,1457.0,767.0,219.0,3056.0,2050.0,801.0,1342.0,...,2160.0,393.0,3027.0,NaN,2436.0,2788.0,1962.0,4264.0,648.0,146.0
7271,Zimbabwe,ZWE,2018,1450.0,795.0,227.0,2918.0,2088.0,825.0,1396.0,...,2240.0,400.0,2890.0,NaN,2509.0,2849.0,2030.0,4377.0,657.0,139.0
7272,Zimbabwe,ZWE,2019,1450.0,812.0,232.0,2884.0,2068.0,827.0,1434.0,...,2292.0,405.0,2855.0,NaN,2554.0,2891.0,2065.0,4437.0,662.0,136.0

In [9]:
df[["country", "code", "year"]].head()

       country code  year
0  Afghanistan  AFG  2007
1  Afghanistan  AFG  2008
2  Afghanistan  AFG  2009
3  Afghanistan  AFG  2011
4  Afghanistan  AFG  2012

In [10]:
df.columns

Index(['country', 'code', 'year', 'meningitis', 'alzheimer's_diesease',
       'parkinson's_disease', 'nutritional_deficiency', 'malaria', 'drowning',
       'interpersonal_violence', 'maternal_disorders', 'hiv/aids',
       'drug_use_disorders', 'tuberculosis', 'cardiovascular_diseases',
       'lower_respiratory_infections', 'neonatal_disorders',
       'alcohol_use_disorders', 'self_harm', 'exposure_to_forces_of_nature',
       'diarrheal_diseases', 'environmental_heat_and_cold_exposure',
       'neoplasms', 'conflict_and_terrorism', 'diabetes_mellitus',
       'chronic_kidney_disease', 'poisonings', 'protein_energy_malnutrition',
       'terrorism', 'road_injuries', 'chronic_respiratory_diseases',
       'chronic_liver_diseases', 'digestive_diseases',
       'fire_heat_hot_substance', 'acute_hepatitis'],
      dtype='object')

In [11]:
df.iloc[0]

country                                 Afghanistan
code                                            AFG
year                                           2007
meningitis                                   2933.0
alzheimer's_diesease                         1402.0
parkinson's_disease                           450.0
nutritional_deficiency                       2488.0
malaria                                       393.0
drowning                                     2127.0
interpersonal_violence                       3657.0
maternal_disorders                           4990.0
hiv/aids                                      148.0
drug_use_disorders                            252.0
tuberculosis                                 4995.0
cardiovascular_diseases                     53962.0
lower_respiratory_infections                27672.0
neonatal_disorders                          23890.0
alcohol_use_disorders                         111.0
self_harm                                    1310.0
exposure_to_forces_of_nature                  296.0
diarrheal_diseases                           9320.0
environmental_heat_and_cold_exposure           57.0
neoplasms                                   15925.0
conflict_and_terrorism                       8220.0
diabetes_mellitus                            3189.0
chronic_kidney_disease                       4490.0
poisonings                                    512.0
protein_energy_malnutrition                  2439.0
terrorism                                    1199.0
road_injuries                                7425.0
chronic_respiratory_diseases                 7222.0
chronic_liver_diseases                       3346.0
digestive_diseases                           6458.0
fire_heat_hot_substance                       481.0
acute_hepatitis                              3437.0
Name: 0, dtype: object

### Get Total Death Per year

In [12]:
len(df.columns)

35

In [13]:
df.iloc[:, 3:35].head()

,meningitis,alzheimer's_diesease,parkinson's_disease,nutritional_deficiency,malaria,drowning,interpersonal_violence,maternal_disorders,hiv/aids,drug_use_disorders,...,chronic_kidney_disease,poisonings,protein_energy_malnutrition,terrorism,road_injuries,chronic_respiratory_diseases,chronic_liver_diseases,digestive_diseases,fire_heat_hot_substance,acute_hepatitis
0,2933.0,1402.0,450.0,2488.0,393.0,2127.0,3657.0,4990.0,148.0,252.0,...,4490.0,512.0,2439.0,1199.0,7425.0,7222.0,3346.0,6458.0,481.0,3437.0
1,2731.0,1424.0,455.0,2277.0,255.0,1973.0,3785.0,5020.0,157.0,261.0,...,4534.0,495.0,2231.0,1092.0,7355.0,7143.0,3316.0,6408.0,462.0,3005.0
2,2460.0,1449.0,460.0,2040.0,239.0,1852.0,3874.0,5013.0,167.0,270.0,...,4597.0,483.0,1998.0,1065.0,7290.0,7045.0,3291.0,6358.0,448.0,2663.0
3,2327.0,1508.0,473.0,1846.0,390.0,1775.0,4170.0,4857.0,184.0,292.0,...,4785.0,483.0,1805.0,1525.0,7432.0,6916.0,3318.0,6370.0,448.0,2365.0
4,2254.0,1544.0,482.0,1705.0,94.0,1716.0,4245.0,4736.0,191.0,305.0,...,4846.0,482.0,1667.0,3521.0,7494.0,6878.0,3353.0,6398.0,445.0,2264.0

In [14]:
df["TotalDeaths"] = df.iloc[:, 3:35].sum(axis=1)

In [15]:
df[["country", "code", "year", "TotalDeaths"]].head()

       country code  year  TotalDeaths
0  Afghanistan  AFG  2007     204796.0
1  Afghanistan  AFG  2008     200209.0
2  Afghanistan  AFG  2009     195927.0
3  Afghanistan  AFG  2011     196559.0
4  Afghanistan  AFG  2012     200364.0

In [17]:
df.groupby(by=["year"], dropna=False).sum().iloc[0]

In [23]:
df.groupby(by=["country"], dropna=False).sum()

,year,meningitis,alzheimer's_diesease,parkinson's_disease,nutritional_deficiency,malaria,drowning,interpersonal_violence,maternal_disorders,hiv/aids,...,poisonings,protein_energy_malnutrition,terrorism,road_injuries,chronic_respiratory_diseases,chronic_liver_diseases,digestive_diseases,fire_heat_hot_substance,acute_hepatitis,TotalDeaths
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,60135,78666.0,41998.0,13397.0,71453.0,13924.0,56536.0,108228.0,129621.0,4282.0,...,14530.0,70163.0,39193.0,208331.0,209857.0,98419.0,186959.0,13559.0,98108.0,6021824.0
African Region (WHO),60135,5325372.0,1252189.0,318566.0,4940860.0,21462693.0,801804.0,2056987.0,2740727.0,28888674.0,...,555599.0,4778253.0,0.0,4839529.0,4564405.0,4578870.0,7763233.0,659574.0,525499.0,225038182.0
Albania,60135,1323.0,16549.0,4491.0,569.0,0.0,2397.0,5242.0,246.0,57.0,...,500.0,526.0,42.0,8522.0,22632.0,8717.0,14907.0,636.0,44.0,523587.0
Algeria,60135,15685.0,86914.0,22943.0,7138.0,70.0,24273.0,16702.0,29475.0,6101.0,...,12337.0,6407.0,11066.0,369395.0,168453.0,91927.0,146527.0,27628.0,10492.0,4612271.0
American Samoa,60135,30.0,143.0,69.0,60.0,0.0,120.0,101.0,30.0,15.0,...,0.0,60.0,0.0,164.0,612.0,181.0,341.0,0.0,0.0,8619.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yemen,60135,21095.0,31045.0,7188.0,68939.0,143463.0,27994.0,17918.0,53611.0,6276.0,...,12561.0,66731.0,8776.0,278327.0,126525.0,64136.0,111536.0,23871.0,26532.0,4097400.0
Yugoslavia,23955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,113.0,0.0,0.0,0.0,0.0,0.0,0.0,113.0
Zaire,11965,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,293.0,0.0,0.0,0.0,0.0,0.0,0.0,293.0
Zambia,60135,98886.0,13473.0,4054.0,95913.0,205529.0,12809.0,30065.0,28395.0,1175563.0,...,9056.0,92915.0,21.0,56976.0,59173.0,100581.0,147640.0,9476.0,8846.0,4110730.0
Zimbabwe,60135,41238.0,20017.0,5764.0,66723.0,118728.0,18169.0,32741.0,29802.0,1836042.0,...,9113.0,65942.0,27.0,67207.0,71774.0,55027.0,108691.0,14718.0,3778.0,4418611.0